{{- if eq .Values.cloudprovider "vsphere" }}
{{- range $index, $nodepool := .Values.nodepools }}
apiVersion: rke-machine-config.cattle.io/v1
kind: VmwarevsphereConfig
metadata:
  name: {{ $nodepool.name }}-{{$index}}-{{ $.Values.cluster.name }}
  namespace: fleet-default
common:
{{- if $nodepool.labels }}
  labels:
{{ toYaml $nodepool.labels | indent 4 }}
{{- end }}
{{- if $nodepool.taints }}
  taints:
{{ toYaml $nodepool.taints | indent 4 }}
{{- end }}
#{{- if $nodepool.cfgparam }}
#cfgparam: {{ $nodepool.cfgparam }}
#{{- end }}
cloneFrom: {{ $nodepool.cloneFrom }}
cpuCount: {{ $nodepool.cpuCount | quote }}
creationType: {{ $nodepool.creationType }}
vcenter: {{ $nodepool.vcenter }}
datacenter: {{ $nodepool.datacenter }}
datastore: {{ $nodepool.datastore }}
datastoreCluster: {{ $nodepool.datastoreCluster }}
diskSize: {{ $nodepool.diskSize | quote }}
folder: {{ $nodepool.folder }}
#hostsystem: {{ $nodepool.hostsystem }}
memorySize: {{ $nodepool.memorySize | quote }}
network: {{ $nodepool.network }}
pool: {{ $nodepool.pool }}
sshPort: {{ $nodepool.sshPort | quote }}
sshUser: {{ $nodepool.sshUser }}
sshUserGroup: {{ $nodepool.sshUserGroup }}
#tag: {{ $nodepool.tag }}
#vappIpallocationpolicy: {{ $nodepool.vappIpallocationpolicy }}
#vappIpprotocol: {{ $nodepool.vappIpprotocol }}
#vappProperty: {{ $nodepool.vappProperty }}
#vappTransport: {{ $nodepool.vappTransport }}
{{- end }}
{{- end }}


